
language: cpp
dist: bionic
compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install libglfw3
  - sudo apt-get install xorg-dev
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libglm-dev
  - sudo apt-get install freeglut3-dev
  
script:
  - cd src/
  - cmake .
  - cmake --build . 
